### ISSUE TITLE
Navigation Items Missing on Desktop View

### ISSUE THREAD

**Issue by SwapnilMk** [SwapnilMk/portfolio-website#4]
### Issue Description
When I open the website on a desktop, only the logo is visible, and the navigation items are not showing.

### Expected Behavior
I expect the navigation items to be visible on the desktop version of the website.

### Actual Behavior
Currently, only the logo is displayed, and the navigation items are missing.

### Steps to Reproduce
1. Open the website on a desktop.

### Additional Information
- Browser: Chrome
- Operating System: Windows 11
- Website URL: https://swapnil-portfolioweb.netlify.app/

**Comment by Sky-De** [comment]
@SwapnilMk hi, assign this to me, i will find and fix the problem
Thanks
