### ISSUE TITLE
Issue: Images Not Loading After Deployment

### ISSUE THREAD

**Issue by SwapnilMk** [SwapnilMk/portfolio-website#6]
### Problem Description:
After deploying my React application, I'm facing an issue where the images are not loading. The error message indicates a 404 (not found) for the image URL.

## Steps to Reproduce
Deploy the React application.
Visit the deployed site.
Observe that the images are not loading.

## Code Details
I have a data.js file that contains an array of objects with image details. These images are accessed in the WorkCard component.

### ERROR message
GET https://swapnil-portfolioweb.netlify.app/src/assets/Projects/techtea.png 404 (Not Found)

## Expected Behavior
Images should load correctly after deployment.

**Comment by LAMSSAOUI** [comment]
### Hello **Swapnil Mahadik** ,
this  is maybe a good ressource https://answers.netlify.com/t/new-to-netlify-errors-loading-a-images-in-a-react-project-don-t-know-how-to-resolve-properly-or-troubleshoot/89124

**Comment by SwapnilMk** [comment]
You're welcome! @LAMSSAOUI  I'm glad you found the resource helpful.
The issue has been resolved !
